version: "3"
services:
  server:
    image: "ghcr.io/sequenc-consortium/qunicorn-core:main"
    networks:
      - qunicorn
    environment:
      CONTAINER_MODE: server
      SERVER_PORT: 8080
      BROKER_URL: "redis://broker:6379"
      DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
    depends_on:
      - postgres
      - broker
    ports:
      - "8080:8080"
    labels:
      kompose.service.expose: "true"
      kompose.service.type: "loadbalancer"

  worker:
    image: "ghcr.io/sequenc-consortium/qunicorn-core:main"
    networks:
      - qunicorn
    environment:
      CONTAINER_MODE: worker
      BROKER_URL: "redis://broker:6379"
      DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
    depends_on:
      - postgres
      - broker
    ports:
      - "6379"

  keycloak:
    image: jboss/keycloak
    networks:
      - qunicorn
    depends_on:
      - keycloak_postgres
    ports:
      - "8081:8080"
    volumes:
      - "./resources/keycloak-realm-export.json:/tmp/realm-export.json"
    environment:
      DB_VENDOR: postgres
      KEYCLOAK_USER: kc_user
      KEYCLOAK_PASSWORD: kc_pass
      DB_ADDR: keycloak_postgres
      DB_USER: postgres
      DB_PASSWORD: passwd
      KEYCLOAK_IMPORT=/tmp/realm-export.json:

  keycloak_postgres:
    image: postgres:15.3
    networks:
      - qunicorn
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data \


  broker:
    image: redis:7.0.12
    networks:
      - qunicorn
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15.3
    networks:
      - qunicorn
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: qunicorn
    volumes:
      - pgdata:/var/lib/postgresql/data \
    ports:
      - "5432:5432"

  qvm:
    image: rigetti/qvm
    networks:
      - qunicorn
    ports:
      - "5555:5555"

  quilc:
    image: rigetti/quilc
    networks:
      - qunicorn
    ports:
      - "5000:5000"

networks:
  qunicorn:

volumes:
  pgdata:
  keycloak_pgdata:

