version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_postgres
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: passwd
      KEYCLOAK_USER: kc_user
      KEYCLOAK_PASSWORD: kc_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY_MODE: edge
      KC_METRICS_ENABLED: true
      KC_HTTP_ENABLED: true
      #KEYCLOAK_IMPORT: /opt/keycloak/data/import/keycloak-realm-export.json
    ports:
      - "8081:8080"
    volumes:
      - ./resources/keycloak-realm-export.json:/opt/keycloak/data/import/keycloak-realm-export.json
    depends_on:
      - keycloak_postgres
    restart: always
    networks:
      - qunicorn

  keycloak_postgres:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passwd
    hostname: local
    restart: always
    volumes:
      - /keycloak_pgdata:/var/lib/postgresql/data
    ports: 
      - "5439:5432"
    networks:
      - qunicorn

networks:
  qunicorn:

volumes:
  pgdata:
  keycloak_pgdata:

