apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: broker
  name: broker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  template:
    metadata:
      labels:
        io.kompose.network/qunicorn-core-qunicorn: "true"
        io.kompose.service: broker
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - image: redis:7.2.5
          name: broker
          env:
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: password
          command: ["redis-server", "--requirepass", "$(BROKER_PASSWORD)"]
          ports:
            - containerPort: 6379
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
