apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: server
  type: LoadBalancer
