name: Runs python tests

on: [push]

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Install poetry gunicorn and invoke
        run: python -m pip install gunicorn invoke pytest
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.0
      - name: Install requirements with poetry
        run: python -m poetry export --without-hashes --format=requirements.txt -o requirements.txt && python -m pip install -r requirements.txt
      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
      - name: Install redis cli # so we can test the server
        run: sudo apt-get install -y redis-tools
      - name: Verify that redis is up
        run: redis-cli ping
      - name: Install pytest-mock
        run: python -m pip install pytest-mock
      - name: Run unit tests
        run: python -m pytest tests


