name: Runs python tests

on: [ push ]

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0
      - name: Install poetry gunicorn and invoke
        run: python -m pip install gunicorn invoke pytest
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest
      - name: Install requirements with poetry
        run: python -m poetry export --without-hashes --format=requirements.txt -o requirements.txt && python -m pip install -r requirements.txt
      - name: Run unit tests
        run: python -m pytest tests/automated_tests
